### ISSUE TITLE
ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

### ISSUE THREAD

**Issue by frroossst** [USSTR-Avionics/Avionics-code#17]
Sometimes platform IO will throw a compiler error, as there is an implicit type conversion from type string to type char* 

TODO:
1. Create a header file for strings, where they are declared as `const char*`
2. Include the header in main.cpp
3. replace strings in main.cpp with const char var names

**Comment by snowy-shadow** [comment]
this?
https://www.geeksforgeeks.org/convert-string-char-array-cpp/
or maybe this?
https://en.cppreference.com/w/cpp/io/basic_stringstream

what is the specific problem you are tring to fix?

**Comment by snowy-shadow** [comment]
I just tested out a random line:
write_to_sd_card(const_cast<char*>("[MICROCONTROLLER] watchdog callback"));
this works fine now

**Comment by snowy-shadow** [comment]
Since std::string is already a `const char*`, assigning the string to `const char*` won't be accepted by the function. 
```
    const char* test = "[MICROCONTROLLER] watchdog callback";
    write_to_sd_card(test);
```
this is giving me squiggly lines. 
removing `const` fixes the error, which is what const_cast<> does

**Comment by frroossst** [comment]
It was giving me a compiler error, but it would only throw a compiler error every now and then? which was weird, put the string in a header, and declared it using `const char*` which fixed the issue. I just assumed everyone else would also get the same compiler error, umm... do you not get the compiler error when the code is just 
```
write_to_sd_card("[MICROCONTROLLER] watchdog callback");

```
If you don't it might be a different compiler version thing. 

What do you think would be the best solution which is also C compatible?

Let's just write everything in Rust.

**Comment by snowy-shadow** [comment]
I'm building just fine after removing `const`, passing in `const char*` gives me about the same error. Only `char*` fixes the issue using platform io. 

If you want to turn any `const` variable into a non `const` variable, you need to copy the entire thing. so `strcpy()` would be our best bet

just saying c++ is not c with classes(exception is pre c++11). I would strong advise against writing c++ as c and vise versa. If you want to do it in c, we should do it properly in c instead of c++. this is almost equivalent to saying in rust, instead of working with the compiler, lets wrap everything in `unsafe`. 
It's common in the embedded world to set restriction on what c++ features to use, but writing proper c++ code is important for readability and maintainablity.
Also, compiler optimization is a big thing, especially in time critical softwares. the compiler is always smarter (unless you are going to start calculating cpu cycles). Therefore, simple code is almost always faster and better code since compiler can predict the intension and optimize base upon that. (sorry i get very worked up about people treating c++ as c with classes, and write pure c code in c++)

We could write everything in rust, the main problem i have is with accessing the FRAM API. That is going to be a pain. I saw your FRAM implementations, they were good, however, either you did not free your pointers and introduced a mem leak, or you passed over a dangling reference pointer(depending what rust does to the ptr after finish excuting). You might want to find a way to fix that.
----------------------------------------------------------------------------------------------------------------
Unrelated sidenote. Statemachines are OO concepts, that means we can't really have statemachines in c. We can hack together a statemachine, however, instead of classes they will be structs and we would need to write our own virutal tables(... etc). Basically we would be implementing all the class features + inheritance of c++ from scratch in c.
